In [1]:
import numpy as np
x_data=np.array([2,4,6,8,10,12,14,16,18,20]).reshape(10,1)
t_data=np.array([0,0,0,0,0,0,1,1,1,1]).reshape(10,1)

x_data=np.array([[2,4],[4,11],[6,6],[8,5],[10,7],[12,16],[14,8],[16,3],[18,7]])
t_data=np.array([0,0,0,0,1,1,1,1,1]).reshape(9,1)

In [2]:
print(x_data)
print(t_data)

[[ 2  4]
 [ 4 11]
 [ 6  6]
 [ 8  5]
 [10  7]
 [12 16]
 [14  8]
 [16  3]
 [18  7]]
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [3]:
w=np.random.rand(2,1)
b=np.random.rand(1)
print(w,b)

[[0.08976283]
 [0.23578154]] [0.61784151]


In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
def loss_func(x,t):
    delta=1e-7 #10의마이너스 7승?
    z=np.dot(x,w)+b
    y=sigmoid(z)
    return -np.sum(t*np.log(y+delta)+(1-t)*np.log((1-y)+delta))

In [6]:
def numerical_derivative(f, x): # 수치미분 debug version
    delta_x = 1e-4 
    grad = np.zeros_like(x) 
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
#     print("debug 1. x = ", x)
#     print("debug 2. grad = ", grad)
#     print("=========================================================")
    while not it.finished:
        idx = it.multi_index

        #print("debug 3. idx=", idx, ", x[idx]= ", x[idx])
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
#         print("debug 4. grad[idx] = ", grad[idx])
#         print("debug 5. grad = ", grad)
#         print("+++++++++++++++++++++++++++++++++++++++++++")


        x[idx] = tmp_val
        it.iternext() 
    return grad

In [7]:
def predict(x):
    z=np.dot(x,w)+b
    y=sigmoid(z)
    
    if y>0.5:
        result=1
    else:
        result=0
    return y,result

In [15]:
learning_rate=1e-4

f=lambda x: loss_func(x_data, t_data)
    
print("Initial error value:", loss_func(x_data, t_data), "Initial w=",w,"Initial b=",b)

for step in range(30001):
    w-=learning_rate * numerical_derivative(f,w)
    b-=learning_rate * numerical_derivative(f,b)
    
    if step%400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=",w,"b=",b)

Initial error value: 1.5095594269755295 Initial w= [[ 0.55606581]
 [-0.01781216]] Initial b= [-4.52207548]
step= 0 error value= 1.509550319979951 w= [[ 0.55606812]
 [-0.01781118]] b= [-4.52210555]
step= 400 error value= 1.5059198770555156 w= [[ 0.55699214]
 [-0.01741901]] b= [-4.53411481]
step= 800 error value= 1.5023139106599825 w= [[ 0.55791378]
 [-0.01702863]] b= [-4.54608347]
step= 1200 error value= 1.4987321651127397 w= [[ 0.55883306]
 [-0.01664001]] b= [-4.55801183]
step= 1600 error value= 1.4951743882686868 w= [[ 0.55974998]
 [-0.01625313]] b= [-4.56990017]
step= 2000 error value= 1.4916403314578337 w= [[ 0.56066457]
 [-0.015868  ]] b= [-4.58174876]
step= 2400 error value= 1.4881297494261083 w= [[ 0.56157683]
 [-0.01548458]] b= [-4.5935579]
step= 2800 error value= 1.4846424002773662 w= [[ 0.56248677]
 [-0.01510286]] b= [-4.60532786]
step= 3200 error value= 1.4811780454165573 w= [[ 0.56339441]
 [-0.01472283]] b= [-4.6170589]
step= 3600 error value= 1.477736449494063 w= [[ 0.56429

In [12]:
# (real_val, logical_val)=predict(13)
# print(real_val, logical_val)

In [17]:
test_data=np.array([8,10])
predict(test_data)

(array([0.42683267]), 0)