In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def numerical_derivative(f, x): # 수치미분 debug version
    delta_x = 1e-4 
    grad = np.zeros_like(x) 
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
#     print("debug 1. x = ", x)
#     print("debug 2. grad = ", grad)
#     print("=========================================================")
    while not it.finished:
        idx = it.multi_index

        #print("debug 3. idx=", idx, ", x[idx]= ", x[idx])
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
#         print("debug 4. grad[idx] = ", grad[idx])
#         print("debug 5. grad = ", grad)
#         print("+++++++++++++++++++++++++++++++++++++++++++")


        x[idx] = tmp_val
        it.iternext() 
    return grad

In [21]:
class LogicGate:
    def __init__(self, gate_name,xdata,tdata):
        self.name=gate_name
        self.__xdata = xdata
        self.__tdata = tdata
        
        self.__xdata = xdata.reshape(4,2)
        self.__tdata = tdata.reshape(4,1)
        
        self.__w2=np.random.rand(2,6)
        self.__b2=np.random.rand(1)
        
        self.__w3=np.random.rand(6,1)
        self.__b3=np.random.rand(1)
        
        self.__learning_rate=1e-2
        
    def feed_forward(self):
        delta = 1e-7
        
        z2=np.dot(self.__xdata,self.__w2)+self.__b2
        a2=sigmoid(z2)
        
        z3=np.dot(a2,self.__w3)+self.__b3
        y=sigmoid(z3)
    
        
        return -np.sum(self.__tdata*np.log(y+delta)+(1-self.__tdata)*np.log((1-y)+delta))
     
    def train(self):
        f=lambda x:self.feed_forward()
        print("Initial error value:", self.feed_forward())

        for step in range(10001):
            self.__w2-=self.__learning_rate * numerical_derivative(f,self.__w2)
            self.__b2-=self.__learning_rate * numerical_derivative(f,self.__b2)

            self.__w3-=self.__learning_rate * numerical_derivative(f,self.__w3)
            self.__b3-=self.__learning_rate * numerical_derivative(f,self.__b3)

            if step%400==0:
                print("step=", step, "error value=", self.feed_forward())
    
    def predict(self, xdata):
        z2=np.dot(xdata,self.__w2)+self.__b2
        a2=sigmoid(z2)
        
        z3=np.dot(a2,self.__w3)+self.__b3
        y=sigmoid(z3)

        if y>=0.5:
            result=1
        else:
            result=0
        return y,result

In [22]:
xdata=np.array([[0,0],[0,1],[1,0],[1,1]])
tdata=np.array([0,0,0,1])

and_obj=LogicGate("AND",xdata,tdata)
and_obj.train()

Initial error value: 7.594021631016206
step= 0 error value= 7.2895102788392645
step= 400 error value= 2.3108224132842854
step= 800 error value= 2.2543361591121194
step= 1200 error value= 2.1917861960032052
step= 1600 error value= 2.066019198518186
step= 2000 error value= 1.84431197519651
step= 2400 error value= 1.641414275900242
step= 2800 error value= 1.474406395398066
step= 3200 error value= 1.32998270940643
step= 3600 error value= 1.2013058593522459
step= 4000 error value= 1.0791005140855772
step= 4400 error value= 0.9559845539255862
step= 4800 error value= 0.830784273403167
step= 5200 error value= 0.7082609874470978
step= 5600 error value= 0.5954230572726549
step= 6000 error value= 0.4974627827594318
step= 6400 error value= 0.4160848256841045
step= 6800 error value= 0.35024111914498146
step= 7200 error value= 0.29758500783176456
step= 7600 error value= 0.2555384450800504
step= 8000 error value= 0.22180358740145079
step= 8400 error value= 0.19451397416521873
step= 8800 error value= 

In [23]:
test_data = np.array([[0,0],[0,1],[1,0],[1,1]])

for data in test_data:
    print(and_obj.predict(data))


(array([0.00507271]), 0)
(array([0.02708149]), 0)
(array([0.03868439]), 0)
(array([0.94787371]), 1)
