In [1]:
import numpy as np

In [2]:
load_data = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [3]:
load_data

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [4]:
x_data = load_data[:,:-1]
t_data = load_data[:,[-1]]
print(x_data)
print(t_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [5]:
w = np.random.rand(3,1) # 3x1행렬
b = np.random.rand(1)
print(w,b)

[[0.96175934]
 [0.54586851]
 [0.68238269]] [0.35210232]


In [6]:
def loss_func(x,t):
    y=np.dot(x,w)+b
    return (np.sum((t-y)**2))/len(x)

In [7]:
def numerical_derivative(f,x):
    delta_x= 1e-4
    grad = np.zeros_like(x)
    
#     print("debug 1. initial input variable =", x)
#     print("debug 2. initial grad =", grad)
#     print("=====================================")
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        
#         print("debug 3. idx=", idx, ", x[idx]=", x[idx])
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = float(tmp_val) - delta_x
        fx2 = f(x) #f(x-delta_X)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
#         print("debug 4. grad[idx]=", grad[idx])
#         print("debug 5. grad =", grad)
#         print("=====================================")
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [8]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [10]:
learning_rate=1e-2

f=lambda x: loss_func(x_data, t_data)
    
print("Initial error value:", loss_func(x_data, t_data), "Initial w=",w,"Initial b=",b)

for step in range(200001):
    w-=learning_rate * numerical_derivative(f,w)
    b-=learning_rate * numerical_derivative(f,b)
    
    if step%400==0:
        print("step=", step, "error value=", loss_func(x_data, t_data), "w=",w,"b=",b)

Initial error value: 6.377381815964974e+33 Initial w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] Initial b= [-5.85678855e+09]
step= 0 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.85678855e+09]
step= 400 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.85678855e+09]
step= 800 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.85678855e+09]
step= 1200 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.85678855e+09]
step= 1600 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.85678855e+09]
step= 2000 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.85678855e+09]
step= 2400 error value= 6.377381815964974e+33 w= [[3.29392482e+14]
 [3.29389133e+14]
 [3.29378256e+14]] b= [-5.856788