In [1]:
a=10
b=10
a+b

20

In [2]:
def my_func1(x):
    return x**2

In [3]:
def numerical_drivative(f,x):
    delta_x=1e-4
    return (f(x+delta_x)-f(x-delta_x))/(2*delta_x)

In [4]:
result=numerical_drivative(my_func1,3)
print("result=",result)

result= 6.000000000012662


In [5]:
import numpy as np

In [6]:
def my_func2(x):
    return 3*x*(np.exp(x))

In [7]:
result = numerical_drivative(my_func2,2)
print("result=",result)

result= 66.50150507518049


In [8]:
def numerical_derivative(f, x): 
    delta_x = 1e-4 
    grad = np.zeros_like(x) 
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        print(grad[idx])
        print(grad)
        print("="*20)
        
        x[idx] = tmp_val
        it.iternext() 
    return grad

In [9]:
def func2(input_obj):
    x=input_obj[0]
    y=input_obj[1]
    return (2*x+3*x*y+np.power(y,3))

In [12]:
numerical_derivative(func2, np.array([3.0, 2.0]))

7.999999999999119
[8. 0.]
21.000000010040765
[ 8.         21.00000001]


array([ 8.        , 21.00000001])

In [16]:
def func3(input_obj):
    w=input_obj[0]
    x=input_obj[1]
    y=input_obj[2]
    z=input_obj[3]
    return (w*x+x*y*z+3*w+z*np.power(y,2))

In [17]:
numerical_derivative(func3, np.array([3.0, 2.0, 3.0, 4.0]))

5.000000000023874
[5. 0. 0. 0.]
15.000000000000568
[ 5. 15.  0.  0.]
31.999999999996476
[ 5. 15. 32.  0.]
15.000000000000568
[ 5. 15. 32. 15.]


array([ 5., 15., 32., 15.])